### ISSUE TITLE
Osc and VRC wont connect

### ISSUE THREAD

**Issue by Nightinpink** [DASPRiD/vrc-osc-manager#4]
Hey i bought your toggle and followed the whole tutorial process and everything, it worked just fine until i looged out of vrchat and the next day in vrchat. i looked for trouble solving even deleted the OSC in %appdata% etc on your gumroad but nothing.. it just wont work, it shows the toggle from the vrc pishock controller in the osc debug, the pishocker reacts to the controller on the website but vrchat just dont send infos to the osc like i can turn it off and on over and over again but it wont give me a notification that it sends to the osc... which means it just dont work anymore for me i tried it on a different avatar. same problem nothing helps i tried recreating everything. nothing...please i need help

**Comment by DASPRiD** [comment]
Was resolved in private.
