### ISSUE TITLE
OSC Manager Crashes Instantly on Launch

### ISSUE THREAD

**Issue by SamHayzen** [DASPRiD/vrc-osc-manager#5]
Howdy, I have the version of this from the PiShock setup.

This is my current config:
```
[osc]
send_port = 9000
recieve_port = 9001

[pishock]
username = "samhayzen"
api_key = "[my key]"
codes = ["my code"]
duration = 1
```

And this is the error out I keep getting:
```
23:07:22 [INFO] Starting plugins
23:07:22 [ERROR] Unable to add subsystem, parent subsystem already shutting down!
23:07:22 [ERROR] Program crash occurred: at least one subsystem returned an error
23:09:12 [INFO] Starting VRC OSC Manager v2.1.0
23:09:12 [INFO] OSC running on UDP port 54287
23:09:12 [ERROR] Error in subsystem 'OscQuery': I/O error: An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call. (os error 10042) (IPv4)
23:09:12 [INFO] Initiating shutdown ...
23:09:12 [ERROR] Program crash occurred: at least one subsystem returned an error
```

I don't have anything currently using ports 9000 or 54287, and I allowed it through my antivirus

Thank you <3

**Comment by SamHayzen** [comment]
I ran the old, legacy version instead and it worked.

**Comment by DASPRiD** [comment]
Which OS are you running on?

**Comment by SamHayzen** [comment]
Running windows 10.
When I said I downgraded and it worked, I spoke too soon.  It just says my code "doesn't exist", despite the code very much existing.

**Comment by DASPRiD** [comment]
That message you see is directly from PiShock's API, so your config might be incorrect. 

Anyway, regarding the IO error you were seeing, lemme compile you a version with upgraded dependencies later this week so you can test if that fixes it for you.

**Comment by SamHayzen** [comment]
I've already talked to the pishock people, and they directed me to here about it lol, I've already tried a few codes.  Are you sure it should be a string _array_ and not just a string?

I'll be happy to test the new version when you have it available.

**Comment by DASPRiD** [comment]
Without seeing more of your config, I can't really help there. You could just partially mask your values maybe.

As for an updated version, please try out this:
[vrc-osc-manager.zip](https://github.com/DASPRiD/vrc-osc-manager/files/15000858/vrc-osc-manager.zip)

**Comment by SamHayzen** [comment]
Just tried the updated version and it appears to be more of the same:
```
22:25:12 [INFO] Initiating shutdown ...
22:27:13 [INFO] Starting VRC OSC Manager v2.1.0
22:27:13 [INFO] OSC running on UDP port 50475
22:27:13 [ERROR] Uncaught error from subsystem '/OscQuery': I/O error: An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call. (os error 10042) (IPv4)
22:27:13 [INFO] Shutting down ...
22:27:13 [WARN] Shutdown finished with errors.
22:27:13 [ERROR] Program crash occurred: at least one subsystem returned an error
```

**Comment by DASPRiD** [comment]
Okay, this is really strange, considering it works for everyone else.

**Comment by DASPRiD** [comment]
Could it be that your networking stack is IPv6 only? Though that'd be really weird.

**Comment by DASPRiD** [comment]
Closing as there was no feedback in a while.
